version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
  backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/projekitap
      - JWT_SECRET=supersecretkey
      - JWT_EXPIRES_IN=1d
    depends_on:
      - mongo
      - redis
      - rabbitmq
volumes:
  mongo-data:
